<?php

namespace Ivoz\Core\Infrastructure\Persistence\Doctrine;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Ivoz\Core\Domain\Model\Commandlog\Commandlog;
use Ivoz\Core\Domain\Model\Commandlog\CommandlogRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * CommandlogDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @template-extends ServiceEntityRepository<Commandlog>
 */
class CommandlogDoctrineRepository extends ServiceEntityRepository implements CommandlogRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Commandlog::class);
    }
}
